version: '3'

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: "pgadmin_container"
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ravenp.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pg-network
  postgres:
    restart: always
    image: postgres:alpine
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ravenp
      POSTGRES_PASSWORD: test
      POSTGRES_DB: learn_postgres
    volumes:
      - pgvol:/var/lib/postgresql/data
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  pgvol:
  pgadmin:
